import { Router } from 'express';
import healthRoutes from './health';
import authRoutes from './auth';
import userRoutes from './users';
import roleRoutes from './roles';
import permissionRoutes from './permissions';
import auditLogRoutes from './auditLogs';
import providerRoutes from './providers';
import accountTypeRoutes from './accountTypes';
import accountRoutes from './accounts';
import typeRoutes from './types';
import transactionRoutes from './transactions';
import balanceRoutes from './balances';
import transferRoutes from './transfers';
import loadingRoutes from './loading';
import reconciliationRoutes from './reconciliation';
import alertRoutes from './alerts';
import reportRoutes from './reports';
import settingsRoutes from './settings';
import transactionFeeRoutes from './transactionFees';
import profileRoutes from './profile';
import importRoutes from './import';
import bankReconciliationRoutes from './bankReconciliation';
import searchRoutes from './search';
import additionalChargeRoutes from './additionalCharges';
import customerRoutes from './customers';
import backupRoutes from './backup';

const router = Router();

router.use(healthRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/providers', providerRoutes);
router.use('/account-types', accountTypeRoutes);
router.use('/accounts', accountRoutes);
router.use('/transaction-types', typeRoutes);
router.use('/transactions', transactionRoutes);
router.use('/balances', balanceRoutes);
router.use('/transfers', transferRoutes);
router.use('/loading', loadingRoutes);
router.use('/reconciliations', reconciliationRoutes);
router.use('/alerts', alertRoutes);
router.use('/reports', reportRoutes);
router.use('/settings', settingsRoutes);
router.use('/transaction-fees', transactionFeeRoutes);
router.use('/profile', profileRoutes);
router.use('/import', importRoutes);
router.use('/bank-reconciliation', bankReconciliationRoutes);
router.use('/search', searchRoutes);
router.use('/additional-charges', additionalChargeRoutes);
router.use('/customers', customerRoutes);
router.use('/backup', backupRoutes);

export default router;
